CREATE TABLE USER_TB (
  ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(30) UNIQUE,
  EMAIL VARCHAR(255) UNIQUE,
  PASSWORD_HASHED VARCHAR(255),
  ROLE VARCHAR(20) DEFAULT 'ROLE_USER',
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  CREATED_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DESCRIPTION VARCHAR(500),
  PRIMARY KEY (ID)
)

DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;



# Password hashed with Bcrypt and round number 10
# from [Bcrypt-Generator.com - Online Bcrypt Hash Generator & Checker](https://bcrypt-generator.com/)

# password = 'admin'
INSERT INTO USER_TB (USERNAME, EMAIL, PASSWORD_HASHED, ROLE) VALUE ('admin', 'admin@email.com', '$2y$10$6GK91MWJ1ttjJUecZ33jfeRjypKgCaG1PurrVzs69P8V1F1osVwqW', 'ROLE_ADMIN');

# password = 'test'
INSERT INTO USER_TB (USERNAME, EMAIL, PASSWORD_HASHED, ROLE) VALUE ('test', 'test@email.com', '$2y$10$ZWR87DVck5gYwCpQ4U3etuGVb0bJsoFd6n4eKL9yPtZGqtSFPcdGK', 'ROLE_USER');
