# Spring profile setup and global configuration
spring:
  profiles:
    active: local

---
# SPRING PROFILE: LOCAL

# A base url which indicates an ip address of api provider.
api:
  web-client:
    base-url: "http://localhost:8888"

server:
  port: 8080

spring:
  profiles: local
